/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentinelRouteImport } from './routes/sentinel'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as IndexRouteImport } from './routes/index'

const SentinelRoute = SentinelRouteImport.update({
  id: '/sentinel',
  path: '/sentinel',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/sentinel': typeof SentinelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/sentinel': typeof SentinelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coverage': typeof CoverageRoute
  '/sentinel': typeof SentinelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coverage' | '/sentinel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coverage' | '/sentinel'
  id: '__root__' | '/' | '/coverage' | '/sentinel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverageRoute: typeof CoverageRoute
  SentinelRoute: typeof SentinelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentinel': {
      id: '/sentinel'
      path: '/sentinel'
      fullPath: '/sentinel'
      preLoaderRoute: typeof SentinelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverageRoute: CoverageRoute,
  SentinelRoute: SentinelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
